#!/usr/bin/env bash
set -euo pipefail

# Compute SMVS/Bi-SMVS and select SMVS/Bi-SMVS spoofing positions for
# CBD_Building_01. Requires clean_01 and, for GRAPH_SOURCE=lio_sam, proxy graph
# dumps generated by prepare_fast_livo2_cbd01_lio_proxy_graph.sh.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_ROOT="${DATA_ROOT:-$HOME/catkin_ws/datasets/official/fast_livo2}"
SEQUENCE="${SEQUENCE:-CBD_Building_01}"
BAG="${BAG:-$DATA_ROOT/raw_rosbags/FAST-LIVO2-Dataset/FAST-LIVO2官方数据集/${SEQUENCE}.bag}"
OUT_ROOT="${OUT_ROOT:-$DATA_ROOT/experiments_${SEQUENCE}}"

BAG="$BAG" \
OUT_ROOT="$OUT_ROOT" \
CLEAN_CSV="${CLEAN_CSV:-$OUT_ROOT/runs/clean_01/clean_01_traj.csv}" \
SEQUENCE="$SEQUENCE" \
GRAPH_SOURCE="${GRAPH_SOURCE:-lio_sam}" \
GRAPH_DUMP_DIR="${GRAPH_DUMP_DIR:-$OUT_ROOT/lio_proxy_graph_dumps}" \
IMAGE_TOPIC="${IMAGE_TOPIC:-/left_camera/image}" \
DISTANCE_THRESHOLD="${DISTANCE_THRESHOLD:-15}" \
SPOOFING_RANGE="${SPOOFING_RANGE:-80}" \
MIN_TRAJ_DIST="${MIN_TRAJ_DIST:-8}" \
MAX_TRAJ_DIST="${MAX_TRAJ_DIST:-14}" \
PLAY_RATE="${PLAY_RATE:-1.0}" \
bash "$SCRIPT_DIR/prepare_fast_livo2_method_positions.sh"
