#!/usr/bin/env bash
set -euo pipefail

# Supplemental LVI-SAM sweeps after the main x15 experiments.
# Defaults:
#   1) SMVS static range sweep: 15/40, 15/60, 15/80
#   2) Bi-SMVS removal range sweep: 15/40, 15/60, 15/80
#   3) Bi-SMVS static trigger-distance sweep at R=60: D=10 and D=20
#
# Bi-SMVS static range sweep is not repeated here because it was already
# generated by run_handheld_bismvs_static_param_sweep_x3.sh.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUN_SMVS_STATIC_RANGE="${RUN_SMVS_STATIC_RANGE:-1}"
RUN_BISMVS_REMOVAL_RANGE="${RUN_BISMVS_REMOVAL_RANGE:-1}"
RUN_BISMVS_STATIC_DISTANCE="${RUN_BISMVS_STATIC_DISTANCE:-1}"

run_step() {
    local label="$1"
    shift
    echo
    echo "============================================================"
    echo "[SUPP] $label"
    echo "============================================================"
    "$@"
}

if [[ "$RUN_SMVS_STATIC_RANGE" == "1" ]]; then
    run_step "SMVS static range sweep x3" \
        bash "$SCRIPT_DIR/run_handheld_smvs_static_param_sweep_x3.sh"
fi

if [[ "$RUN_BISMVS_REMOVAL_RANGE" == "1" ]]; then
    run_step "Bi-SMVS removal range sweep x3" \
        bash "$SCRIPT_DIR/run_handheld_bismvs_removal_param_sweep_x3.sh"
fi

if [[ "$RUN_BISMVS_STATIC_DISTANCE" == "1" ]]; then
    run_step "Bi-SMVS static distance sweep x3 at R=60" \
        bash "$SCRIPT_DIR/run_handheld_bismvs_static_distance_sweep_x3.sh"
fi

echo
echo "[SUPP] Done. Refresh summaries with:"
echo "python3 $SCRIPT_DIR/summarize_attack_exposure.py"
